[package]
name = "telexide"
version = "0.1.4"
description = "An async Rust library for the telegram bot API."
documentation = "https://docs.rs/telexide"
repository = "https://github.com/baev1/telexide"
homepage = "https://github.com/baev1/telexide"
keywords = ["telegram", "api", "bot"]
license-file = "LICENSE.md"
readme = "README.md"
authors = ["Callidus <callidusumbra@gmail.com>"]
edition = "2018"

[dependencies.telexide_proc_macros]
path = "./telexide_proc_macros"
version = "0.1.0"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"
hyper = "0.13"
hyper-tls = "0.5"
tokio = { version = "0.2", features = ["rt-threaded", "tcp", "time", "macros", "sync", "signal"] }
http = "0.2.1"
async-trait = "0.1"
futures = "0.3"
typemap = "0.3"
parking_lot = "0.11"
paste = "0.1"
log = "0.4"
