[package]
name = "webhook_bot"
version = "0.1.0"
authors = ["my name <my@email.address>"]
edition = "2018"

[dependencies]
telexide = { path = "../../" }
tokio = { version = "1", features = ["full"] }
